[features]
seeds = false
[programs.localnet]
true_random_oracle = "rand1Bj6Hftpmmr3KdjZxMpryEUBd19B9dofzXXpQWX"
keno = "kenofas1oZFZvrTg75fLuBatmXSxLcCpNqTsnDCGY99"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/kelliott/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --exit"
